test = {   'name': 'q1a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> summation(1)\n6',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> summation(2)\n54',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> summation(100)\n153015000',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
