test = {   'hidden': False,
    'name': 'q1b',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> u.shape\n(1000, 3)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> s.shape\n(3,)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> vt.shape\n(3, 3)',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> round(s[0], 5)\n103.76854',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
