test = {   'hidden': False,
    'name': 'q1b',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> 0 <= q1b_answer <= 1\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
