test = {   'hidden': False,
    'name': 'q1a',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> len(trend_df)\n32',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> len(trend_df.columns)\n21',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
