test = {   'hidden': False,
    'name': 'q2a2',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> 16 < loss < 17\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
