test = {   'hidden': False,
    'name': 'q1a',
    'points': 5,
    'suites': [   {   'cases': [   {   'code': '>>> 19.5 < xbar < 20.0\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 2.9 < ybar < 3.1\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 8.5 < stdx < 9.0\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 1.3 < stdy < 1.5\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> 0.67 < r < 0.68\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
