test = {   'name': 'q4a',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> abs_loss(3, 5)\n2',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> abs_loss(0, 5)\n5',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> abs_loss(-1, -10)\n9',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> abs_loss(-1, 10)\n11',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
