test = {   'hidden': False,
    'name': 'q5a',
    'points': 4,
    'suites': [   {   'cases': [   {   'code': '>>> bike_sample.shape[0]\n1000',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
